// js/mockdata.js

const today = new Date();
const formatDate = (date) => date.toLocaleDateString("th-TH");
const isoDate = (date) => date.toISOString().split("T")[0];
const dayAgo = (days) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
};

export const MOCK_DATA = {
  user: {
    name: "TANAPAT 'GUY' (ACTIVE STUDENT)",
    avatar: "👨‍💻",
    education: "B.ED. ENGLISH & INNOVATION EDUCATION",
    motto: "Study Hard, Work Harder, Watch Series Hardest",
  },
  timeContext: {
    semester: "2/2025",
    currentTerm: "Final Prep",
    countdown: 15,
  },
  home: {
    mood: "Productive",
    daily_quote: "The best way to predict the future is to create it.",
  },
  goals: [
    {
      id: "g1",
      title: "โปรเจกต์ 'ค่ายภาษาพาเพลิน' เพื่อเด็กดอย",
      icon: "🏔️",
      expanded: true,
      topics: [
        {
          id: "t1",
          title: "การเตรียมงานอาสา",
          subtopics: [
            {
              id: "s1",
              title: "ระดมทุนและจัดหาสื่อ",
              tasks: [
                {
                  id: "k1",
                  title: "เปิดรับบริจาคหนังสือภาษาอังกฤษมือสอง",
                  isComplete: true,
                },
                {
                  id: "k2",
                  title: "ทำสรุปยอดบริจาคทุนการศึกษา",
                  isComplete: true,
                },
                {
                  id: "k3",
                  title: "ประสานงานกับโรงเรียนปลายทาง",
                  isComplete: true,
                },
                {
                  id: "k4",
                  title: "จัดซื้ออุปกรณ์เครื่องเขียน 50 ชุด",
                  isComplete: false,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "g2",
      title: "วิทยากรบรรยาย 'Innovative Teaching'",
      icon: "🎤",
      expanded: false,
      topics: [
        {
          id: "t2",
          title: "เตรียมเนื้อหาบรรยาย",
          subtopics: [
            {
              id: "s2",
              title: "Presentation",
              tasks: [
                {
                  id: "k5",
                  title: "ออกแบบ Slide ด้วย Canva",
                  isComplete: true,
                },
                {
                  id: "k6",
                  title: "ซ้อมบรรยายเทคนิค Active Learning",
                  isComplete: false,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  today: {
    focus: "สอนคาบเช้า + เย็นนี้ไปปั่นโปรเจกต์ฟรีแลนซ์ 💻",
    mustDo: [
      { id: "td1", title: "สอน ม.1/3 (English Game Night)", completed: true },
      { id: "td2", title: "เตรียมเอกสารทำเรื่องลาไปงานอาสา", completed: true },
      { id: "td3", title: "สรุปคะแนนสอบเก็บคะแนน ม.2", completed: true },
      { id: "td4", title: "แพ็คของบริจาคใส่ลัง", completed: false },
    ],
    niceToDo: [
      { id: "td5", title: "อ่านบทความ Educational Tech", completed: true },
      { id: "td6", title: "อัปโหลดรูปกิจกรรมลงเพจโรงเรียน", completed: false },
    ],
    notes: "นัดประชุมกลุ่มจิตอาสาผ่าน Zoom ตอน 20:00 น.",
    brainDump:
      "มองหาอาสาสมัครเพิ่มสำหรับทริปเดือนหน้า\nอยากหาคอร์สเรียน Python เพิ่ม",
    atmosphere: "sunlight",
  },
  library: [
    {
      id: "m1",
      type: "movie",
      title: "Interstellar",
      author: "Christopher Nolan",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    },
    {
      id: "m2",
      type: "movie",
      title: "The Dark Knight",
      author: "Christopher Nolan",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    },
    {
      id: "m3",
      type: "movie",
      title: "Parasite",
      author: "Bong Joon-ho",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
      id: "m4",
      type: "movie",
      title: "Whiplash",
      author: "Damien Chazelle",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    },
    {
      id: "s1",
      type: "series",
      title: "Breaking Bad",
      author: "AMC",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    },
    {
      id: "s2",
      type: "series",
      title: "Better Call Saul",
      author: "AMC",
      status: "reading",
      cover: "https://image.tmdb.org/t/p/w500/iBzrbCvKSB1KJ5yN1YF5gM3mshU.jpg",
    },
    {
      id: "s3",
      type: "series",
      title: "Stranger Things",
      author: "Netflix",
      status: "reading",
      cover: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    },
    {
      id: "s4",
      type: "series",
      title: "Game of Thrones",
      author: "HBO",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    },
    {
      id: "b1",
      type: "book",
      title: "Atomic Habits",
      author: "James Clear",
      status: "done",
      cover: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
    },
    {
      id: "b2",
      type: "book",
      title: "Deep Work",
      author: "Cal Newport",
      status: "reading",
      cover: "https://images-na.ssl-images-amazon.com/images/I/81JJ7fyyKyS.jpg",
    },
    {
      id: "b3",
      type: "book",
      title: "1984",
      author: "George Orwell",
      status: "done",
      cover: "https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg",
    },
    {
      id: "mg1",
      type: "manga",
      title: "Attack on Titan",
      author: "Hajime Isayama",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/2/37846.jpg",
    },
    {
      id: "mg2",
      type: "manga",
      title: "Jujutsu Kaisen",
      author: "Gege Akutami",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/210341.jpg",
    },
    {
      id: "mg3",
      type: "manga",
      title: "One Piece",
      author: "Eiichiro Oda",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/2/253146.jpg",
    },
    {
      id: "mg4",
      type: "manga",
      title: "Chainsaw Man",
      author: "Tatsuki Fujimoto",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    },
    {
      id: "l7",
      type: "manga",
      title: "Spy x Family",
      author: "Tatsuya Endo",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/219741.jpg",
    },
    {
      id: "l8",
      type: "manga",
      title: "Solo Leveling",
      author: "Chugong",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    },
    {
      id: "l9",
      type: "manga",
      title: "Blue Lock",
      author: "Muneyuki Kaneshiro",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/222162.jpg",
    },
  ],
  schedule: [
    {
      id: "sch1",
      date: isoDate(dayAgo(1)),
      title: "กิจกรรมแนะแนวสัญจร",
      timeStart: "09:00",
      timeEnd: "15:00",
      type: "work",
      period: "morning",
      important: true,
    },
    {
      id: "sch2",
      date: isoDate(today),
      title: "สอน ม.1/3 (Active English)",
      timeStart: "08:30",
      timeEnd: "10:30",
      type: "work",
      period: "morning",
      important: true,
    },
    {
      id: "sch3",
      date: isoDate(today),
      title: "อบรมครูออนไลน์ (Coding)",
      timeStart: "13:00",
      timeEnd: "15:30",
      type: "work",
      period: "afternoon",
      important: false,
    },
    {
      id: "sch4",
      date: isoDate(today),
      title: "กิจกรรมจิตอาสา (แจกอาหาร)",
      timeStart: "17:30",
      timeEnd: "19:30",
      type: "life",
      period: "evening",
      important: true,
    },
    {
      id: "sch5",
      date: isoDate(today),
      title: "ประชุมอาสาผ่าน Zoom",
      timeStart: "20:00",
      timeEnd: "21:30",
      type: "work",
      period: "evening",
      important: false,
    },
    {
      id: "sch6",
      date: isoDate(dayAgo(-1)),
      title: "นัดเจอทีมงานค่ายอาสา",
      timeStart: "10:00",
      timeEnd: "12:00",
      type: "life",
      period: "morning",
      important: true,
    },
  ],
  tools: {
    money: {
      budget: 15000,
      categories: {
        expense: [
          { icon: "🍱", label: "อาหาร" },
          { icon: "🎁", label: "ของบริจาค" },
          { icon: "🚗", label: "ค่าน้ำมันอาสา" },
          { icon: "📚", label: "หนังสือใหม่" },
          { icon: "☕", label: "กาแฟ" },
          { icon: "🎮", label: "เติมเกม" },
        ],
        income: [
          { icon: "🏦", label: "เงินเดือน" },
          { icon: "🎨", label: "งานฟรีแลนซ์" },
        ],
      },
      transactions: [
        {
          id: 1,
          type: "income",
          category: "เงินเดือน",
          amount: 32000,
          note: "Full-time Job",
          date: formatDate(dayAgo(7)),
          rawDate: dayAgo(7),
        },
        {
          id: 2,
          type: "income",
          category: "งานฟรีแลนซ์",
          amount: 5000,
          note: "เขียน Content",
          date: formatDate(dayAgo(2)),
          rawDate: dayAgo(2),
        },
        {
          id: 3,
          type: "expense",
          category: "ของบริจาค",
          amount: 1500,
          note: "ซื้อขนมไปแจกเด็ก",
          date: formatDate(dayAgo(3)),
          rawDate: dayAgo(3),
        },
        {
          id: 4,
          type: "expense",
          category: "กาแฟ",
          amount: 85,
          note: "Cafe ก่อนเข้าเวร",
          date: formatDate(today),
          rawDate: today,
        },
        {
          id: 5,
          type: "expense",
          category: "ค่าน้ำมันอาสา",
          amount: 800,
          note: "ไปกลับโรงเรียนปลายทาง",
          date: formatDate(dayAgo(1)),
          rawDate: dayAgo(1),
        },
        {
          id: 6,
          type: "expense",
          category: "เติมเกม",
          amount: 1200,
          note: "Battle Pass",
          date: formatDate(dayAgo(5)),
          rawDate: dayAgo(5),
        },
      ],
    },
    habits: [
      {
        id: "h1",
        name: "ดื่มน้ำ 3 ลิตร",
        color: "var(--color-blue)",
        streak: 20,
        lastDone: formatDate(today),
      },
      {
        id: "h2",
        name: "แชร์ความรู้ลง Facebook",
        color: "var(--color-yellow)",
        streak: 15,
        lastDone: formatDate(today),
      },
      {
        id: "h3",
        name: "อ่านหนังสือวิชาชีพ",
        color: "var(--color-purple)",
        streak: 7,
        lastDone: formatDate(today),
      },
      {
        id: "h4",
        name: "ออกกำลังกายลดพุง",
        color: "var(--color-red)",
        streak: 0,
        lastDone: null,
      },
    ],
    journal: [
      {
        id: "j1",
        date: dayAgo(1),
        text: "วันนี้ไปดูพื้นที่ค่ายมา เหนื่อยแต่รอยยิ้มเด็กๆ มีพลังมาก",
        gratitude: "ขอบคุณทีมอาสา",
        mood: "😊",
        tags: ["Volunteer", "Travel"],
        isFeatured: false,
      },
      {
        id: "j2",
        date: today,
        text: "สอนวันนี้สนุกมาก ใช้เกมช่วยเด็กๆ แย่งกันตอบ",
        gratitude: "ขอบคุณนวัตกรรมใหม่ๆ",
        mood: "🤩",
        tags: ["Teaching", "Success"],
        isFeatured: true,
      },
    ],
    exercise: {
      profile: {
        weight: "62",
        height: "168",
        age: "25",
        gender: "m",
        activity: 1.5,
        goalMin: 180,
        goalCal: 2000,
      },
      logs: [
        { id: "ex1", date: today, type: "เดินแจกของ", duration: 60, cals: 250 },
      ],
    },
  },
  reviews: [
    {
      id: "rv1",
      date: isoDate(dayAgo(7)),
      type: "weekly",
      score: 9,
      content: "คุ้มค่ามาก ได้ทำทั้งงานหลักและงานอาสา",
      positive: "คุมงบได้เป๊ะ",
      negative: "ไม่มีเวลาพัก",
      action: "หาสปาไปนวด",
    },
  ],
  wishlist: [
    {
      id: "w1",
      item: "iPad Air M2",
      price: 23900,
      priority: "High",
      status: "Saving",
    },
    {
      id: "w2",
      item: "ตั๋วเครื่องบินไปญี่ปุ่น",
      price: 18000,
      priority: "Medium",
      status: "Planned",
    },
    {
      id: "w3",
      item: "Mechanical Keyboard",
      price: 4500,
      priority: "Low",
      status: "Wish",
    },
  ],
  travel_plans: [
    {
      id: "tp1",
      destination: "Chiang Mai",
      date: "Dec 2025",
      budget: 12000,
      activities: ["Hiking", "Cafe Hopping"],
      status: "Confirmed",
    },
    {
      id: "tp2",
      destination: "Tokyo",
      date: "Apr 2026",
      budget: 50000,
      activities: ["Akihabara", "Disneyland"],
      status: "Dream",
    },
  ],
  settings: { language: "th", theme: "dark" },
};

