export const MOCK_DATA = {
  user: {
    name: "T. Nattawat",
    avatar: "◈",
    education: "B.Ed. in Mathematics Education",
  },
  today: {
    focus: "ตรวจข้อสอบกลางภาค ม.5/2 และ ม.5/5",
    mustDo: [
      { id: "m1", title: "เตรียมสไลด์สอนเรื่อง เลขยกกำลัง", completed: true },
      { id: "m2", title: "กรอกคะแนนเก็บลงระบบทะเบียน", completed: false },
      {
        id: "m3",
        title: "นัดพบนักเรียนที่ติด ร. ช่วงพักเที่ยง",
        completed: false,
      },
    ],
    niceToDo: [
      {
        id: "n1",
        title: "ทำวิจัยชั้นเรียน (Action Research)",
        completed: false,
      },
      { id: "n2", title: "จัดบอร์ดหน้าห้องเรียนใหม่", completed: true },
    ],
    notes: "ห้อง 5/2 มีนักเรียนลาป่วย 3 คน ต้องนัดสอบซ่อม",
    brainDump: "ไอเดียทำเกมคณิตศาสตร์โดยใช้ Kahoot ผสมกับบอร์ดเกมในคาบหน้า",
    atmosphere: "silence",
  },
  goals: [
    {
      id: "g1",
      title: "พัฒนาสื่อการสอนดิจิทัล (EdTech Expert)",
      icon: "🧠",
      expanded: true,
      topics: [
        {
          id: "t1",
          title: "Learning Management",
          subtopics: [
            {
              id: "s1",
              title: "Google Classroom",
              tasks: [
                {
                  id: "k1",
                  title: "อัปโหลดใบงานวิชาพื้นฐานทั้งหมด",
                  isComplete: true,
                },
                {
                  id: "k2",
                  title: "สร้าง Quiz แบบตัดเกรดอัตโนมัติ",
                  isComplete: false,
                },
              ],
            },
          ],
        },
        {
          id: "t2",
          title: "Professional Development",
          subtopics: [
            {
              id: "s2",
              title: "PLC (วิชาชีพครู)",
              tasks: [
                {
                  id: "k3",
                  title: "ร่วมกลุ่มแลกเปลี่ยนเทคนิคการสอน",
                  isComplete: true,
                },
                {
                  id: "k4",
                  title: "เขียนแผนการจัดการเรียนรู้แบบ Active Learning",
                  isComplete: false,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "g2",
      title: "สอบบรรจุ / เลื่อนวิทยฐานะ",
      icon: "📚",
      expanded: false,
      topics: [
        {
          id: "t3",
          title: "Preparation",
          subtopics: [
            {
              id: "s3",
              title: "Exam Prep",
              tasks: [
                { id: "k5", title: "อ่านกฎหมายทางการศึกษา", isComplete: true },
                {
                  id: "k6",
                  title: "ติวภาค ก. (ภาษาไทย/คณิตศาสตร์)",
                  isComplete: false,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  library: [
    {
      id: "lib1",
      type: "book",
      title: "สอนอย่างไรให้เด็กอยากเรียน",
      author: "Dr. William Glasser",
      cover:
        "https://cdn.pixabay.com/photo/2015/07/27/20/16/book-863418_1280.jpg",
      status: "reading",
    },
    {
      id: "m1",
      type: "movie",
      title: "Interstellar",
      author: "Christopher Nolan",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    },
    {
      id: "m2",
      type: "movie",
      title: "The Dark Knight",
      author: "Christopher Nolan",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    },
    {
      id: "m3",
      type: "movie",
      title: "Parasite",
      author: "Bong Joon-ho",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    },
    {
      id: "m4",
      type: "movie",
      title: "Whiplash",
      author: "Damien Chazelle",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    },
    {
      id: "s1",
      type: "series",
      title: "Breaking Bad",
      author: "AMC",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    },
    {
      id: "s2",
      type: "series",
      title: "Better Call Saul",
      author: "AMC",
      status: "reading",
      cover: "https://image.tmdb.org/t/p/w500/iBzrbCvKSB1KJ5yN1YF5gM3mshU.jpg",
    },
    {
      id: "s3",
      type: "series",
      title: "Stranger Things",
      author: "Netflix",
      status: "reading",
      cover: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    },
    {
      id: "s4",
      type: "series",
      title: "Game of Thrones",
      author: "HBO",
      status: "done",
      cover: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    },
    {
      id: "b1",
      type: "book",
      title: "Atomic Habits",
      author: "James Clear",
      status: "done",
      cover: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
    },
    {
      id: "b2",
      type: "book",
      title: "Deep Work",
      author: "Cal Newport",
      status: "reading",
      cover: "https://images-na.ssl-images-amazon.com/images/I/81JJ7fyyKyS.jpg",
    },
    {
      id: "b3",
      type: "book",
      title: "1984",
      author: "George Orwell",
      status: "done",
      cover: "https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg",
    },
    {
      id: "mg1",
      type: "manga",
      title: "Attack on Titan",
      author: "Hajime Isayama",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/2/37846.jpg",
    },
    {
      id: "mg2",
      type: "manga",
      title: "Jujutsu Kaisen",
      author: "Gege Akutami",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/210341.jpg",
    },
    {
      id: "mg3",
      type: "manga",
      title: "One Piece",
      author: "Eiichiro Oda",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/2/253146.jpg",
    },
    {
      id: "mg4",
      type: "manga",
      title: "Chainsaw Man",
      author: "Tatsuki Fujimoto",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    },
    {
      id: "l7",
      type: "manga",
      title: "Spy x Family",
      author: "Tatsuya Endo",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/219741.jpg",
    },
    {
      id: "l8",
      type: "manga",
      title: "Solo Leveling",
      author: "Chugong",
      status: "done",
      cover: "https://cdn.myanimelist.net/images/manga/3/222295.jpg",
    },
    {
      id: "l9",
      type: "manga",
      title: "Blue Lock",
      author: "Muneyuki Kaneshiro",
      status: "reading",
      cover: "https://cdn.myanimelist.net/images/manga/3/222162.jpg",
    },
  ],
  schedule: [
    {
      id: "sc1",
      date: "2026-01-07",
      title: "สอน ม.5/2 (คณิตศาสตร์)",
      timeStart: "08:30",
      timeEnd: "10:10",
      type: "work",
      period: "morning",
      important: true,
    },
    {
      id: "sc2",
      date: "2026-01-07",
      title: "ประชุมฝ่ายวิชาการ",
      timeStart: "13:00",
      timeEnd: "14:30",
      type: "work",
      period: "afternoon",
      important: false,
    },
    {
      id: "sc3",
      date: "2026-01-07",
      title: "คุมชุมนุม/กิจกรรมลดเวลาเรียน",
      timeStart: "15:30",
      timeEnd: "16:30",
      type: "work",
      period: "afternoon",
      important: false,
    },
  ],
  tools: {
    money: {
      budget: 20000,
      transactions: [
        {
          id: 1,
          rawDate: "2026-01-01",
          type: "income",
          category: "เงินเดือน",
          amount: 18000,
          note: "เงินเดือนครูอัตราจ้าง/ครูฝึกสอน",
        },
        {
          id: 2,
          rawDate: "2026-01-05",
          type: "expense",
          category: "ของใช้",
          amount: 450,
          note: "ซื้ออุปกรณ์เครื่องเขียนให้นักเรียน",
        },
        {
          id: 3,
          rawDate: "2026-01-07",
          type: "expense",
          category: "อาหาร",
          amount: 80,
          note: "โรงอาหารโรงเรียน",
        },
      ],
      categories: {
        expense: [
          { icon: "🍔", label: "อาหาร" },
          { icon: "🚗", label: "เดินทาง" },
          { icon: "🏠", label: "ของใช้" },
          { icon: "🛍️", label: "ช้อปปิ้ง" },
        ],
        income: [
          { icon: "💰", label: "เงินเดือน" },
          { icon: "💼", label: "ฟรีแลนซ์" },
          { icon: "📈", label: "ลงทุน" },
        ],
      },
    },
    habits: [
      {
        id: "h1",
        name: "เขียนแผนการสอนล่วงหน้า",
        color: "var(--color-blue)",
        streak: 4,
        lastDone: "7/1/2569",
      },
      {
        id: "h2",
        name: "ดื่มน้ำระหว่างสอน",
        color: "var(--color-green)",
        streak: 10,
        lastDone: "7/1/2569",
      },
      {
        id: "h3",
        name: "เดินให้ครบ 8,000 ก้าว",
        color: "var(--color-orange)",
        streak: 2,
        lastDone: null,
      },
    ],
    journal: [
      {
        id: "j1",
        date: "2026-01-07T17:00:00.000Z",
        text: "วันนี้สอน ม.5/2 เข้าใจเนื้อหาดีมาก มีเด็กยกมือถามเยอะขึ้น รู้สึกภูมิใจ",
        gratitude: "ขอบคุณหัวหน้าหมวดที่ช่วยแนะนำการจัดการห้องเรียน",
        mood: "🤩",
        tags: ["งาน", "ความรู้สึก"],
        isFeatured: true,
      },
    ],
    exercise: {
      profile: {
        weight: "65",
        height: "170",
        age: "24",
        gender: "m",
        activity: 1.3,
        goalMin: 150,
        goalCal: 2000,
      },
      logs: [
        { id: 101, date: "2026-01-06", type: "เดิน", duration: 40, cals: 120 },
      ],
    },
  },
  reviews: [
    {
      id: 1,
      date: "2026-01-04T21:00:00.000Z",
      week: 1,
      year: 2026,
      action: {
        q1: "ส่งแผนการสอนครบตามกำหนดสัปดาห์แรก",
        q2: "การคุมห้องเรียนในช่วงบ่ายยังทำได้ไม่ดี เด็กสมาธิสั้น",
        q3: "ต้องลองหากิจกรรมนันทนาการมาคั่นระหว่างสอน",
      },
    },
  ],
};
